# Generated by Django 3.1.6 on 2022-05-18 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
