# Generated by Django 3.1.6 on 2022-05-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220521_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bid_count',
        ),
    ]
