# Generated by Django 3.1.6 on 2022-04-24 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220409_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listining',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=b'I01\n', related_name='watchList', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
