# Generated by Django 3.1.6 on 2022-05-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220518_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
