# Generated by Django 3.1.6 on 2022-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20220521_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='auctions/static/auctions/images/defaultImage.png', null=True, upload_to='auctions/static/auctions/images'),
        ),
    ]
